language: cpp

branches:
  only:
    - master

matrix:
  include:
    # - os: linux
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #       packages:
    #         - g++-7
    #   env:
    #     - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - wget https://cmake.org/files/v3.11/cmake-3.11.2-Linux-x86_64.tar.gz -O /tmp/cmake.tgz
  - tar -zxvf /tmp/cmake.tgz
  - export PATH=$PWD/cmake-3.11.2-Linux-x86_64/bin:$PATH

script:
  - mkdir -p build && cd build && export PATH=$PATH:$PWD
  - cmake --version
  - cmake ..
  - make
  - make test
