name: Build and test

on:
  push:
    branches:
      - master

jobs:
  build-test-MacOS:
    name: Build then unit test binaries on MacOS
    runs-on: macOS-latest
    steps:
      - name: Install build tools
        run: |
          brew update
          brew install gcc@9
          brew upgrade cmake
      - name: Clone repo
        uses: actions/checkout@v1
      - name: Compile then test
        run: |
          mkdir build
          cd build
          cmake -D CMAKE_CXX_COMPILER="$(which g++-9)" ..
          make
          make install
          make test
  build-test-linux:
    name: Build then unit test binaries on Linux
    runs-on: ubuntu-18.04
    steps:
      - name: Install build tools
        run: |
          wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | sudo apt-key add -
          sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main'
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt update
          sudo apt install cmake
          sudo apt install g++-8
      - name: Clone repo
        uses: actions/checkout@v1
      - name: Compile then test
        run: |
          /usr/bin/cmake --version
          export CXX=g++-8
          mkdir build
          cd build
          export PATH=$PATH:$PWD
          /usr/bin/cmake -D CMAKE_CXX_COMPILER="$(which g++-8)" ..
          make
          make test
